# Generated by Django 4.0.6 on 2022-07-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
