# Generated by Django 4.0.6 on 2022-07-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customer_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='coins',
            field=models.FloatField(default=0.0),
        ),
    ]
