# Generated by Django 4.0.6 on 2022-07-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_name_customer_username'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.good')),
            ],
        ),
    ]
