# Generated by Django 4.0.6 on 2022-07-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coins_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
